sonar.projectKey=graciasdios9999-prog_automatizacion-inteligente
sonar.organization=graciasdios9999-prog
sonar.sources=src
sonar.exclusions=src/routes/**,frontend/**,src/index.js,src/server.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
